/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package banco.Empleado;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import quick.dbtable.DBTable;

/**
 *
 * @author ng_gu
 */
public class VentanaPrestamo extends javax.swing.JFrame {
    
    private String legajo_empleado;
    private int nro_cliente;
    private VentanaEmpleado ventana_empleado;
    private DBTable tabla;
    private Connection conexionBD;
    private int monto_prestamo;
    private int cant_meses;
    private float tasa_interes;
    private float interes;
    private float valor_cuota;
    
    /**
     * Creates new form VentanaPrestamo
     */
    public VentanaPrestamo(String legajo_empleado, int nro_cliente, VentanaEmpleado ventana_empleado, Connection connection, DBTable tabla) {
        super();
        this.legajo_empleado = legajo_empleado;
        this.nro_cliente = nro_cliente;
        this.ventana_empleado = ventana_empleado;
        this.conexionBD = connection;
        this.tabla = tabla;
        initComponents();
        GUI();
    }
    
    private void GUI() {
        setPreferredSize(new Dimension(1200, 800));
        this.setBounds(0, 0, 1200, 800);
        setLocationRelativeTo(null);
        setVisible(true);
        BorderLayout thisLayout = new BorderLayout();
        this.setTitle("Nuevo préstamo");
        getContentPane().setLayout(thisLayout);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNuevoPrestamo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnIngresarMonto = new javax.swing.JButton();
        txtMonto = new javax.swing.JTextField();
        panelPeriodos = new javax.swing.JPanel();
        lblSeleccionarPeriodo = new javax.swing.JLabel();
        scrollPanelPeriodos = new javax.swing.JScrollPane();
        TablaPeriodos = new javax.swing.JTable();
        btnSeleccionarPeriodo = new javax.swing.JButton();
        panelTasaInteres = new javax.swing.JPanel();
        lblSeleccionarTasaInteres = new javax.swing.JLabel();
        scrollPanelPeriodos1 = new javax.swing.JScrollPane();
        TablaTasaInteres = new javax.swing.JTable();
        btnSeleccionarTasaInteres = new javax.swing.JButton();
        panelCrearPrestamo = new javax.swing.JPanel();
        lblCrearPrestamo = new javax.swing.JLabel();
        txtMontoCrear = new javax.swing.JTextField();
        lblMontoCrear = new javax.swing.JLabel();
        lblCantMesesCrear = new javax.swing.JLabel();
        txtCantMesesCrear = new javax.swing.JTextField();
        lblTasaInteresCrear = new javax.swing.JLabel();
        txtTasaInteresCrear = new javax.swing.JTextField();
        lblInteresCrear = new javax.swing.JLabel();
        txtInteresCrear = new javax.swing.JTextField();
        txtValorCuotaCrear = new javax.swing.JTextField();
        lblValorCuotaCrear = new javax.swing.JLabel();
        txtLegajoCrear = new javax.swing.JTextField();
        lblLegajoCrear = new javax.swing.JLabel();
        txtClienteCrear = new javax.swing.JTextField();
        lblClienteCrear = new javax.swing.JLabel();
        btnCrearPrestamo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nuevo Préstamo");

        lblNuevoPrestamo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNuevoPrestamo.setText("Nuevo Préstamo");
        lblNuevoPrestamo.setMaximumSize(new java.awt.Dimension(120, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Monto:");

        btnIngresarMonto.setText("Ingresar monto");
        btnIngresarMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarMontoActionPerformed(evt);
            }
        });

        panelPeriodos.setVisible(true);

        lblSeleccionarPeriodo.setText("Seleccionar periodo");

        TablaPeriodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Periodo"
            }
        ));
        TablaPeriodos.getTableHeader().setReorderingAllowed(false);
        TablaPeriodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPeriodosMouseClicked(evt);
            }
        });
        scrollPanelPeriodos.setViewportView(TablaPeriodos);

        btnSeleccionarPeriodo.setText("Seleccionar periodo");
        btnSeleccionarPeriodo.setEnabled(false);
        btnSeleccionarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPeriodosLayout = new javax.swing.GroupLayout(panelPeriodos);
        panelPeriodos.setLayout(panelPeriodosLayout);
        panelPeriodosLayout.setHorizontalGroup(
            panelPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeriodosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPanelPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeleccionarPeriodo))
                .addGap(31, 31, 31)
                .addComponent(btnSeleccionarPeriodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPeriodosLayout.setVerticalGroup(
            panelPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeriodosLayout.createSequentialGroup()
                .addComponent(lblSeleccionarPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPeriodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarPeriodo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPeriodos.setVisible(true);

        lblSeleccionarTasaInteres.setText("Seleccionar tasa de interés");

        TablaTasaInteres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tasa de interés"
            }
        ));
        TablaTasaInteres.getTableHeader().setReorderingAllowed(false);
        TablaTasaInteres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaTasaInteresMouseClicked(evt);
            }
        });
        scrollPanelPeriodos1.setViewportView(TablaTasaInteres);

        btnSeleccionarTasaInteres.setText("Seleccionar tasa");
        btnSeleccionarTasaInteres.setEnabled(false);
        btnSeleccionarTasaInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarTasaInteresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTasaInteresLayout = new javax.swing.GroupLayout(panelTasaInteres);
        panelTasaInteres.setLayout(panelTasaInteresLayout);
        panelTasaInteresLayout.setHorizontalGroup(
            panelTasaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTasaInteresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTasaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeleccionarTasaInteres)
                    .addGroup(panelTasaInteresLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(scrollPanelPeriodos1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeleccionarTasaInteres)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTasaInteresLayout.setVerticalGroup(
            panelTasaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTasaInteresLayout.createSequentialGroup()
                .addComponent(lblSeleccionarTasaInteres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTasaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeleccionarTasaInteres)
                    .addComponent(scrollPanelPeriodos1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        lblCrearPrestamo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCrearPrestamo.setText("Resumen creación de préstamo");

        txtMontoCrear.setEnabled(false);

        lblMontoCrear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMontoCrear.setText("Monto:");

        lblCantMesesCrear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCantMesesCrear.setText("Cant. meses:");

        txtCantMesesCrear.setEnabled(false);

        lblTasaInteresCrear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTasaInteresCrear.setText("Tasa interés:");

        txtTasaInteresCrear.setEnabled(false);

        lblInteresCrear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblInteresCrear.setText("Interés:");

        txtInteresCrear.setEnabled(false);

        txtValorCuotaCrear.setEnabled(false);
        txtValorCuotaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCuotaCrearActionPerformed(evt);
            }
        });

        lblValorCuotaCrear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblValorCuotaCrear.setText("Valor cuota:");

        txtLegajoCrear.setEnabled(false);
        txtLegajoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLegajoCrearActionPerformed(evt);
            }
        });

        lblLegajoCrear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblLegajoCrear.setText("Legajo:");

        txtClienteCrear.setEnabled(false);
        txtClienteCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteCrearActionPerformed(evt);
            }
        });

        lblClienteCrear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblClienteCrear.setText("Cliente:");

        btnCrearPrestamo.setText("Crear préstamo");
        btnCrearPrestamo.setEnabled(false);
        btnCrearPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearPrestamoLayout = new javax.swing.GroupLayout(panelCrearPrestamo);
        panelCrearPrestamo.setLayout(panelCrearPrestamoLayout);
        panelCrearPrestamoLayout.setHorizontalGroup(
            panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCrearPrestamo)
                    .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                            .addComponent(lblMontoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMontoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCrearPrestamoLayout.createSequentialGroup()
                            .addComponent(lblCantMesesCrear)
                            .addGap(18, 18, 18)
                            .addComponent(txtCantMesesCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                            .addComponent(lblClienteCrear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                            .addComponent(lblLegajoCrear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLegajoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                            .addComponent(lblValorCuotaCrear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValorCuotaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                            .addComponent(lblInteresCrear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInteresCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                            .addComponent(lblTasaInteresCrear)
                            .addGap(18, 18, 18)
                            .addComponent(txtTasaInteresCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearPrestamoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearPrestamo)
                .addGap(63, 63, 63))
        );
        panelCrearPrestamoLayout.setVerticalGroup(
            panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCrearPrestamo)
                .addGap(18, 18, 18)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantMesesCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantMesesCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTasaInteresCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTasaInteresCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInteresCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInteresCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorCuotaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorCuotaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLegajoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegajoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrearPrestamo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNuevoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresarMonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelTasaInteres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPeriodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(panelCrearPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNuevoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarMonto)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelTasaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCrearPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarMontoActionPerformed
        try {
            this.monto_prestamo = Integer.parseInt(this.txtMonto.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Ingrese un monto válido");
            return;
        }
        if(this.monto_prestamo <= 0) {
            JOptionPane.showMessageDialog(null,"Ingrese un monto mayor a 0");
            return;
        }
        int monto_maximo = this.GetMontoMaximo();
        if(this.monto_prestamo > monto_maximo) {
            JOptionPane.showMessageDialog(null,"Debe ingresar un monto menor o igual a "+monto_maximo+".");
            return;
        }
        this.txtMonto.setEnabled(false);
        this.btnIngresarMonto.setEnabled(false);
        this.refrescarTablaPeriodos();
    }//GEN-LAST:event_btnIngresarMontoActionPerformed

    private void btnSeleccionarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPeriodoActionPerformed
        int fila = this.TablaPeriodos.getSelectedRow();
        String periodoSeleccionado = TablaPeriodos.getModel().getValueAt(fila, 0).toString();
        this.cant_meses = Integer.parseInt(periodoSeleccionado);
        this.refrescarTablaTasaInteres(cant_meses);
    }//GEN-LAST:event_btnSeleccionarPeriodoActionPerformed

    private void TablaPeriodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPeriodosMouseClicked
        this.btnSeleccionarPeriodo.setEnabled(true);
    }//GEN-LAST:event_TablaPeriodosMouseClicked

    private void TablaTasaInteresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaTasaInteresMouseClicked
        this.btnSeleccionarTasaInteres.setEnabled(true);
    }//GEN-LAST:event_TablaTasaInteresMouseClicked

    private void btnSeleccionarTasaInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarTasaInteresActionPerformed
        int fila = this.TablaTasaInteres.getSelectedRow();
        String tasaSeleccionada = TablaTasaInteres.getModel().getValueAt(fila, 0).toString();
        this.tasa_interes = Float.valueOf(tasaSeleccionada.trim()).floatValue();
        this.calcularInteresYCuota();
        this.panelCrearPrestamo.setVisible(true);
        this.panelTasaInteres.setEnabled(false);
        this.rellenarValoresPanelCrearPrestamo();
        this.btnCrearPrestamo.setEnabled(true);
    }//GEN-LAST:event_btnSeleccionarTasaInteresActionPerformed

    private void txtValorCuotaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCuotaCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCuotaCrearActionPerformed

    private void txtLegajoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLegajoCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLegajoCrearActionPerformed

    private void txtClienteCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteCrearActionPerformed

    private void btnCrearPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPrestamoActionPerformed
        this.crearPrestamo();
        JOptionPane.showMessageDialog(null, "El préstamo se agregó correctamente.");
        this.setVisible(false);
        this.ventana_empleado.setVisible(true);
    }//GEN-LAST:event_btnCrearPrestamoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        txtMonto.setText("");
        ventana_empleado.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPeriodos;
    private javax.swing.JTable TablaTasaInteres;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearPrestamo;
    private javax.swing.JButton btnIngresarMonto;
    private javax.swing.JButton btnSeleccionarPeriodo;
    private javax.swing.JButton btnSeleccionarTasaInteres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantMesesCrear;
    private javax.swing.JLabel lblClienteCrear;
    private javax.swing.JLabel lblCrearPrestamo;
    private javax.swing.JLabel lblInteresCrear;
    private javax.swing.JLabel lblLegajoCrear;
    private javax.swing.JLabel lblMontoCrear;
    private javax.swing.JLabel lblNuevoPrestamo;
    private javax.swing.JLabel lblSeleccionarPeriodo;
    private javax.swing.JLabel lblSeleccionarTasaInteres;
    private javax.swing.JLabel lblTasaInteresCrear;
    private javax.swing.JLabel lblValorCuotaCrear;
    private javax.swing.JPanel panelCrearPrestamo;
    private javax.swing.JPanel panelPeriodos;
    private javax.swing.JPanel panelTasaInteres;
    private javax.swing.JScrollPane scrollPanelPeriodos;
    private javax.swing.JScrollPane scrollPanelPeriodos1;
    private javax.swing.JTextField txtCantMesesCrear;
    private javax.swing.JTextField txtClienteCrear;
    private javax.swing.JTextField txtInteresCrear;
    private javax.swing.JTextField txtLegajoCrear;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMontoCrear;
    private javax.swing.JTextField txtTasaInteresCrear;
    private javax.swing.JTextField txtValorCuotaCrear;
    // End of variables declaration//GEN-END:variables
    
    private int GetMontoMaximo() {
        
        try{
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            String sql = "SELECT MAX(monto_sup) AS MontoSuperior FROM tasa_prestamo WHERE 1;";
            ps = this.conexionBD.prepareStatement(sql);
            rs = ps.executeQuery();
            if(rs.next()){
                return rs.getInt("MontoSuperior");
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error al ejecutar la consulta.");
            return 0;
        }
        return 0;
    }
    
    private void refrescarTablaPeriodos() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            TablaPeriodos.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            String sql = "SELECT periodo \n" +
                    "FROM tasa_prestamo \n" +
                    "WHERE monto_inf<="+this.monto_prestamo+" AND "+this.monto_prestamo+"<monto_sup";
            ps = conexionBD.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("periodo");
            
            while (rs.next()) {
                
                Object[] filas = new Object[cantidadColumnas];
                
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                
                modelo.addRow(filas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this),
                    ex.getMessage() + "\n",
                    "Error al ejecutar la consulta.",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void refrescarTablaTasaInteres(int periodo) {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            TablaTasaInteres.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            String sql = "SELECT tasa \n" +
                    "FROM tasa_prestamo \n" +
                    "WHERE monto_inf<="+this.monto_prestamo+" AND "+this.monto_prestamo+"<monto_sup AND periodo="+periodo+";";
            ps = conexionBD.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("tasa");
            
            while (rs.next()) {
                
                Object[] filas = new Object[cantidadColumnas];
                
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                
                modelo.addRow(filas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this),
                    ex.getMessage() + "\n",
                    "Error al ejecutar la consulta.",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void calcularInteresYCuota() {
        this.interes = (this.monto_prestamo * this.tasa_interes * this.cant_meses) / 1200;
        this.valor_cuota = (this.monto_prestamo + this.interes) / this.cant_meses;
    }
    
    private void rellenarValoresPanelCrearPrestamo() {
        this.txtMontoCrear.setText(Integer.toString(this.monto_prestamo));
        this.txtCantMesesCrear.setText(Integer.toString(this.cant_meses));
        this.txtTasaInteresCrear.setText(Float.toString(this.tasa_interes));
        this.txtInteresCrear.setText(Float.toString(this.interes));
        this.txtValorCuotaCrear.setText(Float.toString(this.valor_cuota));
        this.txtLegajoCrear.setText(this.legajo_empleado);
        this.txtClienteCrear.setText(Integer.toString(this.nro_cliente));
    }
    
    private void crearPrestamo() {
        int nro_prestamo = this.insertarPrestamo();
        /*Anteriormente se Insertaban los pagos vinculados a un prestamo manuealmente 
          ahora con el trigger eso se realiza de manera automatica*/
        //this.insertarPagos(nro_prestamo, this.cant_meses);
    }
    
    private int insertarPrestamo() {
        int ultimo_id = -1;
        try
        {
            Statement stmt = this.conexionBD.createStatement();
            String sql = "INSERT INTO prestamo (fecha, cant_meses, monto, tasa_interes, interes, valor_cuota, legajo, nro_cliente) " +
                    "VALUES ( CURDATE(), '"+this.cant_meses+"', '"+this.monto_prestamo+"', '"+this.tasa_interes+"', "
                    + " '"+this.interes+"', '"+this.valor_cuota+"', '"+this.legajo_empleado+"', '"+this.nro_cliente+"')";
            stmt.execute(sql);
            stmt.close();
            ultimo_id = this.obtenerUltimoId();            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this,
                    "Se produjo un error al insertar el nuevo préstamo.\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        return ultimo_id;
    }
    
    private int obtenerUltimoId() {
        try{
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            String sql = "SELECT nro_prestamo FROM prestamo ORDER BY nro_prestamo DESC LIMIT 1;";
            ps = this.conexionBD.prepareStatement(sql);
            rs = ps.executeQuery();
            if(rs.next()){
                return rs.getInt("nro_prestamo");
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error al obtener el id del préstamo creado.");
            return -1;
        }
        return -1;
    }
    
    private void insertarPagos(int nro_prestamo, int cant_meses) {
        try
        {
            for (int nro_pago = 1; nro_pago <= cant_meses; nro_pago++) {
                Statement stmt = this.conexionBD.createStatement();
                String sql = "INSERT INTO pago (nro_prestamo, nro_pago, fecha_venc) " +
                    "VALUES ('"+nro_prestamo+"', '"+nro_pago+"', DATE_ADD(CURDATE(), INTERVAL "+nro_pago+" MONTH))";
                stmt.execute(sql);
                stmt.close();
            }            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this,
                    "Se produjo un error al insertar los pagos del préstamo.\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
}
