/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco.Administrador;

import banco.VentanaPrincipal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import quick.dbtable.DBTable;

/**
 *
 * @author chant
 */
public class adminLogin extends javax.swing.JFrame {

    private VentanaPrincipal ventanaPrincipal;
    private VentanaAdmin ventanaAdmin;
    private DBTable tabla;
    private DBTable lista;
    private Connection conexionBD;
    
    public adminLogin(VentanaPrincipal vp, DBTable t, DBTable l) {
        initComponents();
        ventanaPrincipal=vp;
        tabla = t;
        lista = l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoPassword = new javax.swing.JPasswordField();
        botonLogin = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        etiquetaTitulo.setText("Inicio sesión usuario administrador");

        jLabel3.setText("Contraseña:");

        botonLogin.setText("Ingresar");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(botonLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(etiquetaTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLogin)
                    .addComponent(botonSalir))
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.setVisible(false);
        ventanaPrincipal.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        char[] pwArray = campoPassword.getPassword(); 
	String pw = new String(pwArray);  // Convertir el password de array char a string
	conectarBD(pw);
    }//GEN-LAST:event_botonLoginActionPerformed

    private void conectarBD(String pw)
	{
		try
		{
                    String driver ="com.mysql.jdbc.Driver";
                    String servidor = "localhost:3306";
                    String baseDatos = "banco";
                    String usuario = "admin";
                    String clave = pw;
                    String uriConexion = "jdbc:mysql://" + servidor + "/" + baseDatos+"?serverTimezone=UTC";

                    //establece una conexión con la  B.D. "banco"  usando directamante una tabla DBTable    
                    tabla.connectDatabase(driver, uriConexion, usuario, clave);
                    lista.connectDatabase(driver, uriConexion, usuario, clave);
                    this.conexionBD = DriverManager.getConnection(uriConexion, usuario, clave);
                        
			if (tabla.getConnection() != null) {
				JOptionPane.showMessageDialog(null,
						"Conectado exitosamente.");
                            campoPassword.setText("");
                            ventanaAdmin = new VentanaAdmin(pw,this,conexionBD,tabla,lista);
                            this.setVisible(false);
                            ventanaAdmin.setVisible(true);
                            ventanaAdmin.refrescarLista();		
			}
                        
		}catch (SQLException ex)
		{
			JOptionPane.showMessageDialog(null,
					"Contraseña inválida. Ingrese los datos nuevamente.",
					"Error",
					JOptionPane.ERROR_MESSAGE);
                        campoPassword.setText("");
			System.out.println("SQLException: " + ex.getMessage());
			System.out.println("SQLState: " + ex.getSQLState());
			System.out.println("VendorError: " + ex.getErrorCode());
			ex.printStackTrace();
                        
		}catch (Exception e)
		{
			e.printStackTrace();
		}

	}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLogin;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
